server:
  port: 8001
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sino_data?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/chenhua/modules/access/mapper/xml/*.xml